# Book settings
title: Fundamentos de Deep Learning
author: Raúl Ramos, Julián Arias / Universidad de Antioquia
logo: content/local/imgs/fudea.jpg

repository:
   url: https://github.com/rramosp/2021.deeplearning
   branch: master

launch_buttons:
  binderhub_url: ""
  colab_url: https://colab.research.google.com

html:
  google_analytics_id: "UA-43235448-3"

execute:
  execute_notebooks         : off

